@Test
public
void
testExceptionJava7
(
)
{
CtClass
<
?
>
clazz
=
factory
.
Code
(
)
.
createCodeSnippetStatement
(
""
+
"class X {"
+
"public void foo() {"
+
" try{}catch(RuntimeException | Error e){System.exit(0);}"
+
"}"
+
"};"
)
.
compile
(
)
;
CtTry
tryStmt
=
(
CtTry
)
clazz
.
getElements
(
new
TypeFilter
<
>
(
CtTry
.
class
)
)
.
get
(
0
)
;
List
<
CtCatch
>
catchers
=
tryStmt
.
getCatchers
(
)
;
assertEquals
(
1
,
catchers
.
size
(
)
)
;
assertEquals
(
Throwable
.
class
,
catchers
.
get
(
0
)
.
getParameter
(
)
.
getType
(
)
.
getActualClass
(
)
)
;
assertEquals
(
2
,
catchers
.
get
(
0
)
.
getParameter
(
)
.
getMultiTypes
(
)
.
size
(
)
)
;
assertEquals
(
RuntimeException
.
class
,
catchers
.
get
(
0
)
.
getParameter
(
)
.
getMultiTypes
(
)
.
get
(
0
)
.
getActualClass
(
)
)
;
assertEquals
(
Error
.
class
,
catchers
.
get
(
0
)
.
getParameter
(
)
.
getMultiTypes
(
)
.
get
(
1
)
.
getActualClass
(
)
)
;
assertEquals
(
"java.lang.System.exit(0)"
,
catchers
.
get
(
0
)
.
getBody
(
)
.
getStatement
(
0
)
.
toString
(
)
)
;
}
