@Test
public
void
testIssue2860
(
)
{
Launcher
launcher
=
new
Launcher
(
)
;
launcher
.
addInputResource
(
"src/test/resources/spoon/test/noclasspath/exceptions/Bar.java"
)
;
launcher
.
buildModel
(
)
;
CtType
<
Object
>
type
=
launcher
.
getFactory
(
)
.
Type
(
)
.
get
(
"spoon.test.noclasspath.exceptions.Bar"
)
;
CtCatch
c
=
type
.
filterChildren
(
new
TypeFilter
<
CtCatch
>
(
CtCatch
.
class
)
)
.
first
(
)
;
assertEquals
(
"java.lang.Exception"
,
c
.
getParameter
(
)
.
getType
(
)
.
toString
(
)
)
;
assertEquals
(
"java.io.IOException"
,
c
.
getParameter
(
)
.
getMultiTypes
(
)
.
get
(
0
)
.
toString
(
)
)
;
assertEquals
(
"java.lang.InterruptedException"
,
c
.
getParameter
(
)
.
getMultiTypes
(
)
.
get
(
1
)
.
toString
(
)
)
;
assertEquals
(
"InterruptedException"
,
c
.
getParameter
(
)
.
getMultiTypes
(
)
.
get
(
1
)
.
getSimpleName
(
)
.
toString
(
)
)
;
}
