/** 
 * tests conflict of local variable with CtCatchVariable
 */
private
void
conflictWithCatchVariable
(
)
{
@TestTryRename({"-var2","-var3"})
int
var1
=
1
;
try
{
assertTrue
(
var1
==
1
)
;
@TestTryRename({"-var1","var3"})
int
var2
=
2
;
assertTrue
(
var2
==
2
)
;
throw
new
NumberFormatException
(
)
;
}
catch
(
@TestTryRename({"-var1","var2"})
NumberFormatException
var3
)
{
assertTrue
(
var1
==
1
)
;
}
assertTrue
(
var1
==
1
)
;
}
