@Test
public
void
testInsertAfter
(
)
throws
Exception
{
CtMethod
<
Void
>
foo
=
(
CtMethod
<
Void
>
)
assignmentClass
.
getMethods
(
)
.
toArray
(
)
[
0
]
;
CtBlock
<
?
>
body
=
foo
.
getBody
(
)
;
assertEquals
(
3
,
body
.
getStatements
(
)
.
size
(
)
)
;
CtStatement
s
=
body
.
getStatements
(
)
.
get
(
2
)
;
assertEquals
(
"int z = x + y"
,
s
.
toString
(
)
)
;
CtCodeSnippetStatement
stmt
=
factory
.
Core
(
)
.
createCodeSnippetStatement
(
)
;
stmt
.
setValue
(
"System.out.println(x);"
)
;
s
.
insertAfter
(
stmt
)
;
assertEquals
(
4
,
body
.
getStatements
(
)
.
size
(
)
)
;
assertSame
(
stmt
,
body
.
getStatements
(
)
.
get
(
3
)
)
;
assertEquals
(
body
,
stmt
.
getParent
(
)
)
;
}
