@Test
public
void
localVarsInTryCatch
(
)
{
try
{
int
field
=
4
;
assertTrue
(
field
==
4
)
;
throw
new
IllegalArgumentException
(
)
;
}
catch
(
IllegalArgumentException
e
)
{
assertTrue
(
field
==
15
)
;
{
int
field
=
5
;
assertTrue
(
field
==
5
)
;
}
int
field
=
6
;
assertTrue
(
field
==
6
)
;
}
catch
(
Exception
field
)
{
field
.
getMessage
(
)
;
}
}
